name: crypto_currency_app
description: "A crypto currency app that uses CoinGecko API"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  fl_chart: ^1.1.1
  flutter:
    sdk: flutter
  http: ^1.5.0
  intl: ^0.20.2
  lottie: ^3.3.2
  riverpod: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/lottie/